### PR TITLE
Cohort survival

### PR DESCRIPTION
**Pull request by catalamarti**

### CODE REVIEW

**Comment by catalamarti** [comment]
@edward-burn can you provide an opinionated review of this PR as ir is very related with CohortSurvival

**Comment by catalamarti** [comment]
@edward-burn

**Comment by edward-burn** [comment]
Passing this over to @KimLopezGuell :)

@KimLopezGuell could you also add a vignette?

**Comment by catalamarti** [comment]
any update @KimLopezGuell  @edward-burn

**Pull request closed without merging**
